In [3]:
import numpy as np
x = np.array([3,1,2])
print(x)
print(type(x))

[3 1 2]
<class 'numpy.ndarray'>


In [9]:
c = [[1],[1,2]]
d = np.array([[1,1],[1,2]]) #numpy는 행렬
print(d)
for x,y in d:
    print(x,y)

[[1 1]
 [1 2]]
1 1
1 2


In [10]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [13]:
print(x.shape)
print(x.dtype)
print(d.shape) #2행 2열
print(d.ndim) #배열의 차원 수 반환환

(3,)
float64
(2, 2)
2


In [16]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim) #2차원
print(a.shape) #3행 2열

2
(3, 2)


In [17]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim) #3차원
print(a.shape) #(3,2,1)

3
(3, 2, 1)


In [18]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim) #3차원
print(a.shape) #(3,2,2) (1차원에 3개, 2차원에 2개, 3차원에 2개)

3
(3, 2, 2)


In [19]:
ndar1 = np.array([1,2])
ndar2 = np.array([4,5])
np.dot(ndar1, ndar2)

14

In [22]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [26]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten() #1차원 배열로 변환시켜 준다.
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [27]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)
                 

array([[1, 2, 2],
       [3, 3, 4]])

In [28]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [29]:
np.random.randint(5,size=(2,4))

array([[4, 4, 3, 1],
       [4, 1, 0, 4]])

In [30]:
np.random.rand(2,4)

array([[0.28935368, 0.8058395 , 0.75237252, 0.87680029],
       [0.56114024, 0.75381812, 0.69307397, 0.8198067 ]])

In [31]:
rng = np.random.default_rng()

In [32]:
rng.random()

0.6283976062432829

In [33]:
rng.integers(0,10, (2,4))

array([[2, 4, 8, 0],
       [0, 3, 5, 5]], dtype=int64)

In [34]:
ndar = np.array([[6,3],[5,2],[4,1]])
ndar > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [38]:
ndar[ndar > 4]

array([6, 5])

In [39]:
ndar[ndar < 2]

array([1])

In [40]:
ndar[2:]

array([[4, 1]])

In [41]:
ndar[1:]

array([[5, 2],
       [4, 1]])

In [58]:
a = np.array([[1,2],[3,4]])
print(a[a > 1])
print(a)


[2 3 4]
[[1 2]
 [3 4]]
